Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace MVC_Project.Models
{
    public class Employee
    {
        // TODO: use "required" attribute, or modifier?
        [Required]
        [Column("Id")]
        public int Id { get; set; } // [Id] [int] IDENTITY(1,1) NOT NULL
        [Required]
        [Column("Name")]
        public string Name { get; set; } // [Name] [nvarchar](50) NULL
        [Required]
        [Column("Email")]
        public string Email { get; set; } // [Email] [nvarchar](50) NULL
        [Column("Occupation")]
        public string? Occupation { get; set; } // [Occupation] [nvarchar](50) NULL
    }
}

Models/Expense.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_Project.Models
{
    public class Expense
    {
        [Column("Id")] // Helps to ensure correct column mapping
        public int Id { get; set; }
        [Column("Value")]
        public decimal Value { get; set; }
        [Required]
        [Column("Description")]
        public string? Description{ get; set; }
    }
}

Controllers/EmployeeController.cs
using MVC_Project.Models;
using MVC_Project.DAL;
using Microsoft.AspNetCore.Mvc;


namespace MVC_Project.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly MVC_ProjectDBContext _dbContext;
        
        public EmployeeController(MVC_ProjectDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        #region Views
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Employees()
        {
            List<Employee> employees = new List<Employee>();
            using (_dbContext)
            {
                employees = _dbContext.Employees.ToList();
                ViewBag.Employees = employees;
                return View(employees);
            }
        }

        public IActionResult EditEmployee(int id)
        {
            using (_dbContext)
            {
                Employee employeeToEdit = _dbContext.Employees.Single(employee => employee.Id == id);
                return View(employeeToEdit); // returns the view with the same name as the method
            }
        }
        #endregion

        #region Logic
        public IActionResult EditEmployeeRecord(Employee updatedEmployee)
        {
            using (_dbContext)
            {
                _dbContext.Employees.Update(updatedEmployee);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("Employees");
        }
        
        
        #endregion

    }
}

Controllers/ExpenseController.cs
using MVC_Project.DAL;
using MVC_Project.Models;
using Microsoft.AspNetCore.Mvc;


namespace MVC_Project.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly MVC_ProjectDBContext _dbContext;

        public ExpenseController(MVC_ProjectDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        # region Views
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Expenses()
        {
            using (_dbContext)
            {
                var totalExpenses = _dbContext.Expenses.Sum(Expense => Expense.Value);
                ViewBag.TotalExpenses = totalExpenses;
                return View(_dbContext.Expenses.ToList()); // returns the view with the same name as the method
            }
        }

        public IActionResult CreateEditExpense(int? id) // If you create something new, you won't have an Id
        {
            if (id.HasValue) // Edit
            {
                using (var context = new MVC_ProjectDBContext())
                {
                    // Find expense to edit via id
                    var expenseToEdit = context.Expenses.SingleOrDefault(expense => expense.Id == id);
                    return View(expenseToEdit);
                }
            }
            return View();
        }
        # endregion

        public IActionResult DeleteExpense(int id)
        {
            using (_dbContext)
            {
                // SingleOrDefault() takes the first record found where the record id matches the parameter (id)
                Expense? expenseToDelete = _dbContext.Expenses.SingleOrDefault(expense => expense.Id == id);
                if (expenseToDelete != null)
                {
                    _dbContext.Expenses.Remove(expenseToDelete);
                    _dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Expenses");
        }

        public IActionResult CreateEditExpenseForm(Expense model)
        {
            if (model.Id == 0) // Create Expense
            {
                using (_dbContext)
                {
                    var expense = new Expense()
                    {
                        Value = model.Value,
                        Description = model.Description
                    };
                    _dbContext.Expenses.Add(expense);
                    _dbContext.SaveChanges();
                }
            }
            else // Edit Expense
            {
                using (_dbContext)
                {
                    _dbContext.Expenses.Update(model);
                    _dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Expenses");
        }

    }
}

Controllers/HomeController.cs
using MVC_Project.DAL;
using MVC_Project.Models;
using Microsoft.AspNetCore.Mvc;


namespace MVC_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly MVC_ProjectDBContext _dbContext;

        public HomeController(MVC_ProjectDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        # region Views
        public IActionResult Index()
        {
            return View();
        }
        
        # endregion

    }
}

Views/Employee/EditEmployee.cshtml
@{
    ViewData["Title"] = "Edit Employee";
}

@model Employee

<div class="text-center">
    <h1 class="display-4">Edit an expense</h1>
</div>

<form asp-action="EditEmployeeRecord" asp-controller="Employee">
    <input hidden class="form-control" type="number" asp-for="Id"/>

    <label class-"mt-4">Name: </label>
    <input class="form-control" type="text" placeholder="name" asp-for="Name"/>

    <label class-"mt-4">Email: </label>
    <input class="form-control" type="text" placeholder="email" asp-for="Email" />

    <label class-"mt-4">Occupation: </label>
    <input class="form-control" type="text" placeholder="occupation" asp-for="Occupation" />

    <button class="btn btn-primary mt-4" type="submit">Submit employee edits</button>
</form>

Views/Employee/Employees.cshtml
@{
    ViewData["Title"] = "Expenses";
}

@model List<Employee>

<div class="text-center">
    <h1 class="display-4">Employees</h1>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Occupation</th>
                <th>Edit/Delete</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach(var employee in Model)
                {
                    <tr>
                        <td>@employee.Id</td>
                        <td>@employee.Name</td>
                        <td>@employee.Email</td>
                        <td>@employee.Occupation</td>
                        <td>
                            <a asp-action="EditEmployee" asp-route-id="@employee.Id">Edit</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Employee Page";
}

<div class="text-center">
    <h1 class="display-4">Current location: Views/Employee/Index.cshtml</h1>
    <a asp-action="Employees" class="btn btn-primary">Navigate to Employee page</a>
</div>

Views/Expense/CreateEditExpense.cshtml
@{
    ViewData["Title"] = "";
}

@model Expense

<div class="text-center">
    <h1 class="display-4">Create or edit an expense</h1>
</div>

<form asp-action="CreateEditExpenseForm" asp-controller="Expense">
    <input hidden class="form-control" type="number" placeholder="0" asp-for="Id" />

    <label class="mt-4">Value $</label>
    <input class="form-control" type="number" placeholder="0" asp-for="Value" step="0.01" />

    <label class="mt-4">Description</label>
    <input class="form-control" type="text" placeholder="Add a description" asp-for="Description" />

    <button class="btn btn-primary mt-4" type="submit">Submit expense</button>
</form>
 

Views/Expense/Expenses.cshtml
@{
    ViewData["Title"] = "Expenses";
}

@model List<Expense>

<div class="text-center">
    <h1 class="display-4">Expenses</h1>
    <br />
    <h3>Total expenses $@ViewBag.TotalExpenses</h3>
    <br />
    <a asp-action="CreateEditExpense" asp-controller="Expense" class="btn btn-secondary">Create new</a>
    <br/>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Value</th>
                <th>Description</th>
                <th>Edit/Delete</th>
            </tr>
        </thead>
        <tbody>
            @{ foreach(var expense in Model)
                {
                    <tr>
                        <td>@expense.Id</td>
                        <td>@expense.Value</td>
                        <td>@expense.Description</td>
                        <td>
                            <a asp-action="CreateEditExpense" asp-route-id="@expense.Id">Edit</a>
                            <a asp-action="DeleteExpense" asp-route-id="@expense.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Expense/Index.cshtml
@{
    ViewData["Title"] = "Expense Page";
}

<div class="text-center">
    <h1 class="display-4">Current location: Views/Expense/Index.cshtml</h1>
</div>

Views/Home/CreateEditExpense.cshtml
@{
    ViewData["Title"] = "";
}

@* This configures Expense as the model we're talking about *@
@model MVC_Project.Models.Expense

<div class="text-center">
    <h1 class="display-4">Create or edit an expense</h1>
</div>

<form asp-action="CreateEditExpenseForm" asp-controller="Home">
    <input hidden class="form-control" type="number" placeholder="0" asp-for="Id" />

    <label class="mt-4">Value $</label>
    <input class="form-control" type="number" placeholder="0" asp-for="Value" step="0.01" />

    <label class="mt-4">Description</label>
    <input class="form-control" type="text" placeholder="Add a description" asp-for="Description" />

    <button class="btn btn-primary mt-4" type="submit">Submit expense</button>
</form>
 

Views/Home/Expenses.cshtml
@{
    ViewData["Title"] = "Expenses";
}

@model List<Expense>

<div class="text-center">
    <h1 class="display-4">Expenses</h1>
    <br />
    <h3>Total expenses $@ViewBag.TotalExpenses</h3>
    <br />
    <a asp-action="CreateEditExpense" asp-controller="Home" class="btn btn-secondary">Create new</a>
    <br/>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Value</th>
                <th>Description</th>
                <th>Edit/Delete</th>
            </tr>
        </thead>
        <tbody>
            @{ foreach(var expense in Model)
                {
                    <tr>
                        <td>@expense.Id</td>
                        <td>@expense.Value</td>
                        <td>@expense.Description</td>
                        <td>
                            <a asp-action="CreateEditExpense" asp-route-id="@expense.Id">Edit</a>
                            <a asp-action="DeleteExpense" asp-route-id="@expense.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Current location: Views/Home/Index.cshtml</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Expenses">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Employees">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted"></footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>